const data = [
  {
    id: 1,
    name: 'Hikayen',
    postName: 'ozge.cey',
    image: require('../images/profil.jpg'),
    postImage: require('../images/portakal.jpg'),
    like: 25,
    comment: 'View all 4 comments',
    explanation: 'Nothing is as it seems...',
    time: '1 hour ago',
    timeStory: '1h',
    islike: false,
  },
  {
    id: 2,
    name: 'macellan',
    postName: 'macellan',
    image: require('../images/macellan.jpg'),
    postImage: require('../images/fintech.jpeg'),
    like: 360,
    comment: 'View all 4 comments',
    explanation: 'Stay tuned',
    time: '2 hours ago',
    timeStory: '53d',
    islike: false,
  },
  {
    id: 3,
    name: 'ezgiceylan',
    postName: 'ezgiceylan',
    image: require('../images/ezgiceylan.jpeg'),
    postImage: require('../images/oje.jpg'),
    like: 120,
    comment: 'View all 4 comments',
    explanation: 'New nails :)',
    time: '3 hours ago',
    timeStory: '2h',
    islike: false,
  },
  {
    id: 4,
    name: 'catvideos',
    postName: 'catvideos',
    image: require('../images/cat.jpg'),
    postImage: require('../images/catPost.jpg'),
    like: 160,
    comment: 'View all 8 comments',
    explanation: 'An angry cat',
    time: '5 hours ago',
    timeStory: '3h',
    islike: false,
  },
  {
    id: 5,
    name: 'alternatif',
    postName: 'alternatifSuperApp',
    image: require('../images/alternatif.png'),
    postImage: require('../images/Afiş.png'),
    like: 220,
    comment: 'View all 110 comments',
    explanation: 'Stay tuned',
    time: '8 hours ago',
    timeStory: '6h',
    islike: false,
  },
  {
    id: 6,
    name: 'bfy',
    postName: 'bfy',
    image: require('../images/bfy.png'),
    postImage: require('../images/bfyPost.jpg'),
    like: 150,
    comment: 'View all 25 comments',
    explanation: 'Vehicle tracking has never been easier',
    time: '24 hours ago',
    timeStory: '24h',
    islike: false,
  },
];

export default data;
